sonar.projectKey=harshithk951_My-Portfolio
sonar.organization=harshithk951

# Set the source folder
sonar.sources=src

# Exclude build files and dependencies
sonar.exclusions=node_modules/**, dist/**, **/*.css
